# Set like
POST http://localhost:3334/api/like/set-like/6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M2OWY0OWE4ODFhZDljMGY5ZDAwOGQiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY3Mzk2MTU1MSwiZXhwIjoxNjc5MTQ1NTUxfQ.unDH_rMe4jUcIS4cBbJq7ac7YcmeCd9r_U8WW0GEuSc
###

# Remove like
POST http://localhost:3334/api/like/remove-like/30 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2M2OWY0OWE4ODFhZDljMGY5ZDAwOGQiLCJlbWFpbCI6InVzZXIyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY3Mzk2MTU1MSwiZXhwIjoxNjc5MTQ1NTUxfQ.unDH_rMe4jUcIS4cBbJq7ac7YcmeCd9r_U8WW0GEuSc
###
