# Create comment
  POST http://localhost:3334/api/comment HTTP/1.1
  Content-Type: application/json

  {
    "postId": "1",
    "text": "Some text"
  }
###

# Delete comment
  DELETE http://localhost:3334/api/comment/fc5a8523-935e-4ea9-a51d-830af8d9a122 HTTP/1.1
###

# Get comments
  GET http://localhost:3334/api/comment/1 HTTP/1.1
###
